# Generated by Django 3.2 on 2021-05-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksdb', '0003_auto_20210430_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='buy_sell',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
    ]
