# Generated by Django 3.2 on 2021-05-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksdb', '0004_auto_20210503_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
